export const allProducts = [
  {
    id: 1,
    name: "Royal Velvet 3-Seater Sovereing",
    price: 45999,
    originalPrice: 59999,
    discount: "23% OFF",
    rating: 4.8,
    reviewsCount: 124,
    image: "/product-navy.png",
    color: "Navy Blue",
    badge: "Best Seller",
    type: "3-seater",
    material: "velvet",
    style: "luxury",
    room: "living-room",
    feature: "washable-cover",
    description: "Experience the pinnacle of comfort and style with the Sovereign 3-Seater. Crafted with premium royal velvet and a solid teak wood frame, this sofa brings an air of sophistication to any living space.",
    specs: {
      dimensions: "210cm x 95cm x 85cm",
      weight: "65kg",
      assembly: "Free Installation",
      warranty: "10 Years Frame Warranty",
      deliveryTime: "5-7 Business Days"
    },
    colors: [
      { name: "Navy Blue", hex: "#000080" },
      { name: "Emerald", hex: "#50C878" },
      { name: "Charcoal", hex: "#36454F" },
      { name: "Beige", hex: "#F5F5DC" },
    ],
    sizes: ["3 Seater", "2 Seater", "L-Shape", "Sofa Bed"],
    materials: ["Premium Velvet", "Hand-woven Fabric", "Italian Leather"],
    images: ["/product-navy.png", "/product-emerald.png", "/hero-sofa.png", "/cat-l-shape.png"],
  },
  {
    id: 2,
    name: "Emerald Modern Classic",
    price: 38500,
    originalPrice: 45000,
    discount: "14% OFF",
    rating: 4.9,
    reviewsCount: 89,
    image: "/product-emerald.png",
    color: "Green",
    badge: "New Arrival",
    type: "2-seater",
    material: "velvet",
    style: "modern",
    room: "bedroom",
    feature: "modular",
    description: "A contemporary take on traditional luxury. The Emerald Modern Classic features deep tufting and high-resilience foam for hours of comfort.",
    specs: {
      dimensions: "180cm x 90cm x 80cm",
      weight: "50kg",
      assembly: "Free Installation",
      warranty: "5 Years Professional Warranty",
      deliveryTime: "3-5 Business Days"
    },
    colors: [
      { name: "Emerald", hex: "#50C878" },
      { name: "Gold", hex: "#C9A227" },
    ],
    sizes: ["2 Seater", "3 Seater"],
    materials: ["Performance Fabric", "Velvet"],
    images: ["/product-emerald.png", "/product-navy.png", "/hero-sofa.png"],
  },
  {
    id: 3,
    name: "Toscana L-Shape Sofa",
    price: 82000,
    originalPrice: 99000,
    discount: "17% OFF",
    rating: 4.7,
    reviewsCount: 56,
    image: "/hero-sofa.png",
    color: "Cream",
    badge: null,
    type: "l-shape",
    material: "fabric",
    style: "scandinavian",
    room: "living-room",
    feature: "storage",
    description: "The ultimate family sofa. The Toscana L-Shape offers sprawling space and modular flexibility to fit any room corner perfectly.",
    specs: {
      dimensions: "280cm x 160cm x 85cm",
      weight: "95kg",
      assembly: "Professional Crew Required",
      warranty: "8 Years Structure Warranty",
      deliveryTime: "7-10 Business Days"
    },
    colors: [
      { name: "Cream", hex: "#F5F0E6" },
      { name: "Gray", hex: "#808080" },
    ],
    sizes: ["L-Shape (Right)", "L-Shape (Left)", "U-Shape"],
    materials: ["Linen Blend", "Microfiber"],
    images: ["/hero-sofa.png", "/product-navy.png", "/product-emerald.png"],
  },
  {
    id: 4,
    name: "Chesterfield Leather",
    price: 115000,
    originalPrice: 140000,
    discount: "18% OFF",
    rating: 5.0,
    reviewsCount: 42,
    image: "/cat-recliner.png",
    color: "Brown",
    badge: "Premium",
    type: "3-seater",
    material: "leather",
    style: "chesterfield",
    room: "office",
    feature: "smart",
    description: "Timeless elegance in genuine Italian leather. Hand-applied brass studs and deep button tufting define this iconic silhouette.",
    specs: {
      dimensions: "225cm x 100cm x 75cm",
      weight: "80kg",
      assembly: "Free Installation",
      warranty: "Lifetime Frame / 5y Leather Warranty",
      deliveryTime: "10-14 Business Days"
    },
    colors: [
      { name: "Antique Brown", hex: "#4B2E2B" },
      { name: "Black", hex: "#000000" },
    ],
    sizes: ["3 Seater", "2 Seater"],
    materials: ["Top Grain Leather"],
    images: ["/cat-recliner.png", "/hero-sofa.png", "/product-navy.png"],
  },
];
